Update ChatbotApp1.yml

diff --git a/.github/workflows/ChatbotApp1.yml b/.github/workflows/ChatbotApp1.yml
--- a/.github/workflows/ChatbotApp1.yml
+++ b/.github/workflows/ChatbotApp1.yml
@@ -31,11 +31,11 @@ jobs:
         run: nuget restore "ChatbotApp1.sln"
 
       - name: Check & Fix Code Formatting
-        run: dotnet format "ChatbotApp1.sln" || echo "Cod eformatting failed, but continuing"
+        run: dotnet format "ChatbotApp1.sln" || echo "Code formatting failed, but continuing"
         continue-on-error: true
 
       - name: Build Project
-        run: msbuild "ChatbotApp1.sln" /p:Configuration=Releasee
+        run: msbuild "ChatbotApp1.sln" /p:Configuration=Release /p:Platform="Any CPU"
 
       
 
